env:
  PACKER_LOG: 1
  VM_ID: "task-${CIRRUS_TASK_ID}"
  TART_REGISTRY_USERNAME: fkorotkov # GitHub supports only PATs
  TART_REGISTRY_PASSWORD: ENCRYPTED[!82ed873afdf627284305afef4958c85a8f73127b09978a9786ac521559630ea6c9a5ab6e7f8315abf9ead09b6eff6eae!]
  WORKER_NAME_ARM64: dev-mini
  WORKER_NAME_AMD64: dev-mini-amd64

task:
  name: "Install dependencies ($WORKER_NAME)"

  persistent_worker:
    labels:
      name: $WORKER_NAME
      arch: $WORKER_ARCH
    resources:
      tart-vms: 2

  matrix:
    - env:
        WORKER_NAME: $WORKER_NAME_ARM64
        WORKER_ARCH: arm64
    - env:
        WORKER_NAME: $WORKER_NAME_AMD64
        WORKER_ARCH: amd64

  install_dependencies_script:
    - brew install wget qemu cdrtools ansible

task:
  timeout_in: 2h
  depends_on:
    - "Install dependencies ($WORKER_NAME)"

  matrix:
    - name: Ubuntu $VM_RELEASE
      env:
        VM_NAME: "ubuntu"
        matrix:
          - VM_RELEASE: "24.04"
            URL: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img
            LATEST: latest
          - VM_RELEASE: "22.04"
            URL: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img
        WORKER_NAME: $WORKER_NAME_ARM64
        VM_ARCH: "arm64"
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-with-admin-group"
    - name: Omarchy
      env:
        VM_NAME: "omarchy"
        VM_RELEASE: "3.1.5"
        WORKER_NAME: $WORKER_NAME_ARM64
        VM_ARCH: "arm64"
        URL: https://iso.omarchy.org/omarchy-$VM_RELEASE.iso
        IMAGE_FORMAT: raw
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-without-admin-group"
        LATEST: latest
    - name: Debian
      env:
        VM_NAME: "debian"
        VM_RELEASE: "bookworm"
        WORKER_NAME: $WORKER_NAME_ARM64
        VM_ARCH: "arm64"
        URL: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-arm64.qcow2
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-without-admin-group"
        LATEST: latest
    - name: Fedora
      env:
        VM_NAME: "fedora"
        VM_RELEASE: "42"
        WORKER_NAME: $WORKER_NAME_ARM64
        VM_ARCH: "arm64"
        URL: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/aarch64/images/Fedora-Cloud-Base-Generic-42-1.1.aarch64.qcow2
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-without-admin-group"
        LATEST: latest
    - name: Rocky Linux 9
      env:
        VM_NAME: "rocky"
        VM_RELEASE: "9"
        WORKER_NAME: $WORKER_NAME_ARM64
        VM_ARCH: "arm64"
        URL:  https://dl.rockylinux.org/pub/rocky/9/images/aarch64/Rocky-9-GenericCloud-Base.latest.aarch64.qcow2
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-without-admin-group"
        LATEST: latest
    - name: Linux Runner ($VM_RELEASE $VM_ARCH)
      env:
        VM_NAME: "ubuntu"
        matrix:
          - VM_RELEASE: "24.04"
            URL: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-$VM_ARCH.img"
            LATEST: latest
          - VM_RELEASE: "22.04"
            URL: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-$VM_ARCH.img"
        matrix:
          - VM_ARCH: "arm64"
            WORKER_NAME: $WORKER_NAME_ARM64
          - VM_ARCH: "amd64"
            WORKER_NAME: $WORKER_NAME_AMD64
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-with-admin-group"
        CUSTOMIZATION_PATH: "customizations/linux-runner"
        CUSTOMIZATION_IMAGE: "ubuntu-runner-$VM_ARCH"
    - name: Linux Runner w/ GPU ($VM_RELEASE $VM_ARCH)
      depends_on:
        - "Linux Runner ($VM_RELEASE $VM_ARCH)"
      env:
        VM_NAME: "ubuntu"
        matrix:
          - VM_RELEASE: "24.04"
            VM_BASE_NAME: "ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04"
            LATEST: latest
          - VM_RELEASE: "22.04"
            VM_BASE_NAME: "ghcr.io/cirruslabs/ubuntu-runner-amd64:22.04"
        VM_ARCH: "amd64"
        WORKER_NAME: $WORKER_NAME_AMD64
        USER_DATA_FIXTURE: "cloud-init/user-data.distro-with-admin-group"
        CUSTOMIZATION_PATH: "customizations/linux-runner-gpu"
        CUSTOMIZATION_IMAGE: "ubuntu-runner-$VM_ARCH-gpu"

  persistent_worker:
    labels:
      name: $WORKER_NAME
      arch: $VM_ARCH
    resources:
      tart-vms: 1
  env:
    QCOW2_IMAGE: image.qcow2
    RAW_IMAGE: image.raw

  download_cloud_image_disk_script:
    - '[ -z "$URL" ] && { echo "No base VM to build"; exit 0; }'
    - wget --quiet -O "$QCOW2_IMAGE" "$URL" || true

  convert_cloud_image_disk_script:
    - '[ -z "$URL" ] && { echo "No base VM to build"; exit 0; }'
    - qemu-img convert -p -f ${IMAGE_FORMAT:qcow2} -O raw "$QCOW2_IMAGE" "$RAW_IMAGE"

  generate_cloud_init_image_script:
    - '[ -z "$URL" ] && { echo "No base VM to build"; exit 0; }'
    - echo "local-hostname: $VM_NAME" > cloud-init/meta-data
    - cat "$USER_DATA_FIXTURE" > cloud-init/user-data
    - mkisofs -output cloud-init.iso -volid cidata -joliet -rock cloud-init/

  create_vm_script:
    - '[ -z "$URL" ] && { echo "No base VM to build"; exit 0; }'
    - tart create --linux "$VM_ID"
    - mv "$RAW_IMAGE" ~/.tart/vms/"$VM_ID"/disk.img

  initialize_vm_script:
    - '[ -z "$URL" ] && { echo "No base VM to build"; exit 0; }'
    - packer init .
    - packer build -var vm_name="$VM_ID" .

  customize_vm_script:
    - '[ -z "$CUSTOMIZATION_PATH" ] && { echo "Nothing to customize"; exit 0; }'
    - cd "$CUSTOMIZATION_PATH"
    - packer init .
    - packer build -var vm_name="$VM_ID" -var vm_base_name="$VM_BASE_NAME" .

  info_script: tart get "$VM_ID"

  release_without_latest_script:
    - '[ -z "$CIRRUS_CRON" ] && { echo "Only release via cron"; exit 0; }'
    - '[ ! -z "$LATEST" ] && { echo "Skipping script that releases without latest tag"; exit 0; }'
    - export VM_NAME_TO_PUSH="${CUSTOMIZATION_IMAGE:-$VM_NAME}"
    - tart push --populate-cache "$VM_ID" ghcr.io/cirruslabs/"$VM_NAME_TO_PUSH":"$VM_RELEASE"

  release_with_latest_script:
    - '[ -z "$CIRRUS_CRON" ] && { echo "Only release via cron"; exit 0; }'
    - '[ -z "$LATEST" ] && { echo "Skipping script that releases with latest tag"; exit 0; }'
    - export VM_NAME_TO_PUSH="${CUSTOMIZATION_IMAGE:-$VM_NAME}"
    - tart push --populate-cache "$VM_ID" ghcr.io/cirruslabs/"$VM_NAME_TO_PUSH":latest ghcr.io/cirruslabs/"$VM_NAME_TO_PUSH":"$VM_RELEASE"

  always:
    cleanup_script:
      - tart stop "$VM_ID" || true
      - tart delete "$VM_ID" || true
