- hosts: default
  become: true

  tasks:
    - name: update APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_distribution == 'Ubuntu'
    - name: upgrade to a HWE kernel
      apt:
        name: "linux-generic-hwe-{{ ansible_distribution_version }}"
      when: ansible_distribution == 'Ubuntu'
    - name: reboot for the new kernel to take effect and to ensure that a VM is bootable
      reboot:
      when: ansible_distribution == 'Ubuntu'

    # Guest agent for Tart VMs installation: common tasks
    - name: retrieve latest release metadata for Guest agent for Tart VMs
      ansible.builtin.uri:
        url: "https://api.github.com/repos/cirruslabs/tart-guest-agent/releases/latest"
      register: latest_release
    - name: normalize architecture name reported by Ansible to be Golang-like
      set_fact:
        golang_architecture: "{{ mapping.get(ansible_architecture, ansible_architecture) }}"
      vars:
        mapping:
          x86_64: amd64
          aarch64: arm64
    - name: figure out Guest agent for Tart VMs base URL for .deb/.rpm's
      set_fact:
        tart_guest_agent_base_url: "{{
          latest_release.json.assets |
          selectattr('name', 'match', '^tart-guest-agent_.*_linux_' + golang_architecture + '.(deb|rpm)$') |
          map(attribute='browser_download_url') |
          first |
          regex_replace('.(deb|rpm)$', '')
        }}"

    # Guest agent for Tart VMs installation: Debian-based
    - name: install Guest agent for Tart VMs
      apt:
        deb: "{{ tart_guest_agent_base_url }}.deb"
      when: ansible_os_family == 'Debian'

    # Guest agent for Tart VMs installation: RedHat-based
    - name: install Guest agent for Tart VMs
      dnf:
        name: "{{ tart_guest_agent_base_url }}.rpm"
      when: ansible_os_family == 'RedHat'
